// ─────────────────────────────────────────────
//  WanderAI — Central Mock Data Source
// ─────────────────────────────────────────────

export const MOCK_USER = {
  _id: 'usr_001',
  firstName: 'Alex',
  lastName: 'Carter',
  email: 'alex@wanderai.com',
  avatar: '/images/hero.jpg',
  joinedDate: '2024-03-15',
  totalTrips: 4,
  totalSpent: 12450,
};

export const MOCK_TRIPS = [
  {
    _id: 'trip_001',
    title: 'Amalfi Coast Luxury Escape',
    location: 'Amalfi, Italy',
    country: 'Italy',
    category: 'Beach & Coast',
    price: 2299,
    duration: 7,
    images: ['/images/amalfi.jpg', '/images/beach.jpg'],
    rating: 4.9,
    reviewCount: 128,
    maxGroupSize: 12,
    description:
      'Experience the breathtaking beauty of Italy\'s most dramatic coastline. Wind through cliffside villages, savour fresh seafood, and watch sunsets paint the Tyrrhenian Sea in gold. This curated escape blends luxury accommodation with authentic local culture.',
    highlights: [
      'Private boat tour of the Amalfi Coast',
      'Cooking class with a local Michelin-star chef',
      'Exclusive villa stay with infinity pool',
      'Guided tour of Positano and Ravello',
      'Wine tasting in the Campania region',
    ],
    itinerary: [
      { day: 1, title: 'Arrival & Welcome Dinner', description: 'Arrive in Naples, transfer to your clifftop villa, and enjoy a welcome dinner overlooking the coast.' },
      { day: 2, title: 'Positano Exploration', description: 'Wander through the pastel-coloured village of Positano, shop local boutiques, swim in crystal waters.' },
      { day: 3, title: 'Private Boat Tour', description: 'Full-day private boat tour visiting sea caves, hidden beaches, and the island of Capri.' },
      { day: 4, title: 'Cooking Class & Ravello', description: 'Morning cooking class, afternoon visit to the cliff-top gardens of Ravello.' },
      { day: 5, title: 'Leisure & Spa', description: 'Relax at the villa spa, optional yoga, sunset cocktails on the terrace.' },
      { day: 6, title: 'Amalfi Town & Wine Tour', description: 'Visit Amalfi Cathedral, explore local markets, afternoon wine tasting tour.' },
      { day: 7, title: 'Departure', description: 'Farewell breakfast, transfer to Naples airport.' },
    ],
    inclusions: ['Luxury villa accommodation', 'Daily breakfast', 'Private transfers', 'Boat tour', 'Cooking class', 'Wine tasting', 'Expert local guide'],
    exclusions: ['International flights', 'Travel insurance', 'Personal expenses', 'Lunches & dinners (except welcome dinner)'],
    pricing: [
      { type: 'Solo Traveler', price: 2299 },
      { type: 'Couple (per person)', price: 1999 },
      { type: 'Group (4+, per person)', price: 1799 },
    ],
    available: true,
    startDates: ['2026-04-15', '2026-05-01', '2026-06-10', '2026-09-20', '2026-10-05'],
  },
  {
    _id: 'trip_002',
    title: 'Kyoto Cultural Immersion',
    location: 'Kyoto, Japan',
    country: 'Japan',
    category: 'Culture & Heritage',
    price: 1899,
    duration: 10,
    images: ['/images/kyoto.jpg', '/images/mountain.jpg'],
    rating: 4.8,
    reviewCount: 204,
    maxGroupSize: 8,
    description:
      'Immerse yourself in the perfect blend of ancient tradition and modern innovation. Walk through bamboo groves, witness geisha districts at twilight, participate in a traditional tea ceremony, and discover the Zen temples that have defined Japanese spirituality for centuries.',
    highlights: [
      'Private tea ceremony with a tea master',
      'Sunrise visit to Fushimi Inari Shrine',
      'Traditional ryokan stay with onsen',
      'Night walk through Gion geisha district',
      'Day trip to Nara and Osaka',
    ],
    itinerary: [
      { day: 1, title: 'Arrival in Kyoto', description: 'Arrive at Kansai International Airport, shinkansen to Kyoto, check into ryokan.' },
      { day: 2, title: 'Arashiyama & Bamboo Grove', description: 'Morning in the bamboo grove, Tenryu-ji temple, lunch by the Oi River.' },
      { day: 3, title: 'Fushimi Inari Sunrise', description: 'Early sunrise hike through thousand torii gates, afternoon at Nishiki Market.' },
      { day: 4, title: 'Tea Ceremony & Geisha District', description: 'Private tea ceremony, evening stroll through Gion, traditional kaiseki dinner.' },
      { day: 5, title: 'Nara Day Trip', description: 'Visit the great Buddha at Todai-ji, meet the sacred deer, explore Kasuga Shrine.' },
      { day: 6, title: 'Philosopher\'s Path', description: 'Walk the canal-side Philosopher\'s Path, visit Nanzen-ji and Eikan-do temples.' },
      { day: 7, title: 'Osaka Food Tour', description: 'Day trip to Osaka, street food tour of Dotonbori, Osaka Castle visit.' },
      { day: 8, title: 'Cooking Class & Markets', description: 'Japanese cooking class, afternoon at Kyoto Handicraft Centre.' },
      { day: 9, title: 'Leisure & Onsen', description: 'Free day to explore or relax in the ryokan onsen.' },
      { day: 10, title: 'Departure', description: 'Final morning in Kyoto, transfer to airport.' },
    ],
    inclusions: ['Ryokan accommodation', 'Daily breakfast & dinner', 'JR Pass (7-day)', 'Tea ceremony', 'All entrance fees', 'Expert guide', 'Airport transfers'],
    exclusions: ['International flights', 'Travel insurance', 'Lunches', 'Personal shopping'],
    pricing: [
      { type: 'Solo Traveler', price: 1899 },
      { type: 'Couple (per person)', price: 1650 },
      { type: 'Group (4+, per person)', price: 1499 },
    ],
    available: true,
    startDates: ['2026-03-20', '2026-04-01', '2026-10-15', '2026-11-01'],
  },
  {
    _id: 'trip_003',
    title: 'Swiss Alps Adventure',
    location: 'Zermatt, Switzerland',
    country: 'Switzerland',
    category: 'Adventure & Nature',
    price: 3599,
    duration: 8,
    images: ['/images/alps.jpg', '/images/mountain.jpg'],
    rating: 4.9,
    reviewCount: 87,
    maxGroupSize: 10,
    description:
      'Stand in the shadow of the Matterhorn and experience the raw majesty of the Swiss Alps. Whether you\'re an adrenaline-seeking skier, a trail-blazing hiker, or simply searching for alpine serenity, this carefully crafted escape delivers spectacular mountain scenery, world-class facilities, and Swiss precision hospitality.',
    highlights: [
      'Helicopter ride over the Matterhorn',
      'Private ski instruction from Olympic coach',
      'Fondue dinner in a 200-year-old chalet',
      'Glacier Express panoramic train journey',
      'Ice climbing and snowshoeing',
    ],
    itinerary: [
      { day: 1, title: 'Arrival in Zurich', description: 'Arrive in Zurich, scenic train to Zermatt, check into mountain chalet lodge.' },
      { day: 2, title: 'Orientation & Gondola Ride', description: 'Morning orientation hike, afternoon gondola to Schwarzsee glacier plateau.' },
      { day: 3, title: 'Matterhorn Helicopter Tour', description: 'Breathtaking helicopter flight around the Matterhorn glacier.' },
      { day: 4, title: 'Ski Day', description: 'Full-day on the slopes with private ski instructor.' },
      { day: 5, title: 'Glacier Express', description: 'Scenic Glacier Express train journey through the Alps to St. Moritz and back.' },
      { day: 6, title: 'Ice Climbing & Snowshoeing', description: 'Guided ice climbing session, afternoon snowshoeing through alpine forest.' },
      { day: 7, title: 'Leisure & Spa', description: 'Free day: optional skiing or relax at the luxury alpine spa.' },
      { day: 8, title: 'Departure', description: 'Final breakfast, scenic drive back to Zurich airport.' },
    ],
    inclusions: ['Luxury chalet accommodation', 'Full board (all meals)', 'Ski pass (5-day)', 'Helicopter tour', 'Glacier Express ticket', 'Ski instructor', 'Spa access'],
    exclusions: ['International flights', 'Travel insurance', 'Ski equipment rental', 'Personal expenses'],
    pricing: [
      { type: 'Solo Traveler', price: 3599 },
      { type: 'Couple (per person)', price: 3199 },
      { type: 'Group (4+, per person)', price: 2899 },
    ],
    available: true,
    startDates: ['2026-12-20', '2027-01-05', '2027-01-20', '2027-02-10'],
  },
  {
    _id: 'trip_004',
    title: 'Maldives Overwater Paradise',
    location: 'North Malé Atoll, Maldives',
    country: 'Maldives',
    category: 'Beach & Coast',
    price: 4199,
    duration: 6,
    images: ['/images/maldives.jpg', '/images/beach.jpg'],
    rating: 4.7,
    reviewCount: 163,
    maxGroupSize: 6,
    description:
      'Drift away to the ultimate tropical paradise. Your private overwater bungalow sits above the crystal-clear Indian Ocean, where vibrant coral reefs teem with life just steps from your glass floor. This is barefoot luxury at its finest — unhurried, exclusive, and utterly unforgettable.',
    highlights: [
      'Private overwater bungalow with glass floor',
      'Sunrise dolphin watching cruise',
      'Private snorkelling with marine biologist',
      'Sunset dinner on a sandbank',
      'Couples spa in an overwater pavilion',
    ],
    itinerary: [
      { day: 1, title: 'Arrival & Seaplane Transfer', description: 'Arrive at Malé, exclusive seaplane transfer to your resort, welcome drinks.' },
      { day: 2, title: 'Reef Exploration', description: 'Private snorkelling tour with marine biologist over pristine coral gardens.' },
      { day: 3, title: 'Dolphin Cruise', description: 'Sunrise dolphin watching cruise, afternoon of complete relaxation.' },
      { day: 4, title: 'Sandbank Dinner', description: 'Private sandbank picnic lunch, sunset 5-course dinner under the stars.' },
      { day: 5, title: 'Spa & Leisure', description: 'Couples overwater spa, optional kayaking or paddleboarding.' },
      { day: 6, title: 'Departure', description: 'Final morning swim, seaplane back to Malé.' },
    ],
    inclusions: ['Overwater bungalow (5 nights)', 'Full board', 'Seaplane transfers', 'Snorkelling tour', 'Dolphin cruise', 'Sandbank dinner', 'Spa treatment'],
    exclusions: ['International flights', 'Travel insurance', 'Alcoholic beverages', 'Watersports extras'],
    pricing: [
      { type: 'Solo Traveler', price: 4199 },
      { type: 'Couple (per person)', price: 3699 },
    ],
    available: true,
    startDates: ['2026-11-10', '2026-12-01', '2027-01-15', '2027-02-20'],
  },
  {
    _id: 'trip_005',
    title: 'Santorini Sunset Romance',
    location: 'Santorini, Greece',
    country: 'Greece',
    category: 'Beach & Coast',
    price: 2799,
    duration: 7,
    images: ['/images/beach.jpg', '/images/amalfi.jpg'],
    rating: 4.8,
    reviewCount: 219,
    maxGroupSize: 8,
    description:
      'The volcanic island of Santorini offers some of the world\'s most iconic vistas — whitewashed villages perched on caldera cliffs, deep blue domed churches, and sunsets that have inspired artists for centuries. Enjoy private wine tours, catamaran cruises, and exclusive caveside dining.',
    highlights: [
      'Caldera catamaran sunset cruise',
      'Private wine tasting at volcanic vineyards',
      'Exclusive caveside dinner in Oia',
      'Helicopter tour over the Aegean',
      'Photography session at Oia castle',
    ],
    itinerary: [
      { day: 1, title: 'Arrival in Santorini', description: 'Arrive, cable car up from the port, check into caldera-view suite.' },
      { day: 2, title: 'Fira & Imerovigli', description: 'Walk the caldera path from Fira to Imerovigli, explore local galleries.' },
      { day: 3, title: 'Catamaran Cruise', description: 'Full-day catamaran around the island, swimming at volcanic hot springs.' },
      { day: 4, title: 'Wine Tour', description: 'Private tour of 3 volcanic vineyards, learn about Assyrtiko wine.' },
      { day: 5, title: 'Oia & Sunset Photography', description: 'Explore Oia\'s blue-domed churches, iconic sunset session at the castle.' },
      { day: 6, title: 'Akrotiri Archaeological Site', description: 'Visit the Bronze Age ruins, afternoon beach relaxation at Perivolos.' },
      { day: 7, title: 'Departure', description: 'Final morning coffee on the terrace, transfer to airport.' },
    ],
    inclusions: ['Caldera-view suite', 'Breakfast daily', 'Catamaran cruise', 'Wine tour', 'Sunset dinner', 'All transfers'],
    exclusions: ['International flights', 'Travel insurance', 'Lunches', 'Personal shopping'],
    pricing: [
      { type: 'Solo Traveler', price: 2799 },
      { type: 'Couple (per person)', price: 2399 },
      { type: 'Group (4+, per person)', price: 2199 },
    ],
    available: true,
    startDates: ['2026-05-20', '2026-06-15', '2026-09-10', '2026-10-01'],
  },
  {
    _id: 'trip_006',
    title: 'Patagonia Wilderness Trek',
    location: 'Torres del Paine, Chile',
    country: 'Chile',
    category: 'Adventure & Nature',
    price: 3299,
    duration: 12,
    images: ['/images/mountain.jpg', '/images/alps.jpg'],
    rating: 4.9,
    reviewCount: 62,
    maxGroupSize: 8,
    description:
      'At the end of the world lies one of the planet\'s last great wildernesses. Trek through Torres del Paine National Park past granite towers, turquoise lakes, and ancient glaciers. This is a journey to the raw heart of nature — challenging, awe-inspiring, and life-changing.',
    highlights: [
      'W-Trek through Torres del Paine',
      'Private glacier hike on Grey Glacier',
      'Kayaking on Lake Grey',
      'Wildlife spotting (pumas, condors, guanacos)',
      'Luxury eco-lodge accommodation',
    ],
    itinerary: [
      { day: 1, title: 'Arrive Punta Arenas', description: 'Arrive, equipment check, team briefing dinner.' },
      { day: 2, title: 'Transfer & First Trek', description: 'Drive to the park, hike to Mirador Condor.' },
      { day: 3, title: 'Glacier Grey', description: 'Trek to Grey Glacier, kayaking on the turquoise lake.' },
      { day: 4, title: 'Los Cuernos Trail', description: 'Full-day trek through the dramatic Los Cuernos mountain range.' },
      { day: 5, title: 'Valle del Francés', description: 'Hike into the Valle del Francés glacial amphitheatre.' },
      { day: 6, title: 'Rest Day & Wildlife', description: 'Guided wildlife spotting: pumas, guanacos, condors.' },
      { day: 7, title: 'Las Torres Base', description: 'The iconic trek to the base of the three granite towers at sunrise.' },
      { day: 8, title: 'Lago Nordenskjöld', description: 'Lakeside trek, afternoon photography session.' },
      { day: 9, title: 'Rest & Spa', description: 'Recovery day at the eco-lodge wellness centre.' },
      { day: 10, title: 'Final Hike', description: 'Scenic ridge hike with panoramic park views.' },
      { day: 11, title: 'Farewell Dinner', description: 'Celebration dinner, return to Punta Arenas.' },
      { day: 12, title: 'Departure', description: 'Fly home.' },
    ],
    inclusions: ['Luxury eco-lodge (11 nights)', 'All meals', 'Expert guide', 'Park entrance fees', 'Glacier trek', 'Kayaking', 'Equipment'],
    exclusions: ['International flights', 'Travel insurance', 'Personal gear', 'Tips'],
    pricing: [
      { type: 'Solo Traveler', price: 3299 },
      { type: 'Couple (per person)', price: 2999 },
      { type: 'Group (4+, per person)', price: 2699 },
    ],
    available: true,
    startDates: ['2026-11-15', '2026-12-10', '2027-01-20', '2027-02-15'],
  },
  {
    _id: 'trip_007',
    title: 'Marrakech Royal Experience',
    location: 'Marrakech, Morocco',
    country: 'Morocco',
    category: 'Culture & Heritage',
    price: 1499,
    duration: 6,
    images: ['/images/suite.jpg', '/images/mountain.jpg'],
    rating: 4.6,
    reviewCount: 148,
    maxGroupSize: 10,
    description:
      'Lose yourself in the labyrinthine medina of Marrakech, where ancient palaces, fragrant souks, and world-class riads create a sensory spectacle unlike anywhere on Earth. From Berber cooking classes to Atlas Mountain excursions, this royal experience unveils the soul of Morocco.',
    highlights: [
      'Stay in a restored 16th-century riad',
      'Private souk tour with a local historian',
      'Atlas Mountains day trip with Berber lunch',
      'Hammam and traditional spa ritual',
      'Sunset rooftop dinner overlooking the medina',
    ],
    itinerary: [
      { day: 1, title: 'Arrival & Djemaa el-Fna', description: 'Arrive, settle into your riad, evening at the famous square.' },
      { day: 2, title: 'Medina & Souks', description: 'Private souk tour: spices, leather tanneries, carpet markets.' },
      { day: 3, title: 'Atlas Mountains', description: 'Full-day trip to the High Atlas, Berber village, traditional lunch.' },
      { day: 4, title: 'Palaces & Gardens', description: 'Bahia Palace, Saadian Tombs, Majorelle Garden.' },
      { day: 5, title: 'Cooking Class & Hammam', description: 'Morning cooking class, afternoon royal hammam ritual.' },
      { day: 6, title: 'Departure', description: 'Morning souk shopping, farewell mint tea ceremony, airport transfer.' },
    ],
    inclusions: ['Luxury riad (5 nights)', 'Breakfast daily', 'Atlas day trip', 'Souk tour guide', 'Hammam', 'Cooking class', 'Airport transfers'],
    exclusions: ['International flights', 'Travel insurance', 'Most lunches & dinners', 'Personal shopping'],
    pricing: [
      { type: 'Solo Traveler', price: 1499 },
      { type: 'Couple (per person)', price: 1299 },
      { type: 'Group (4+, per person)', price: 1149 },
    ],
    available: true,
    startDates: ['2026-03-10', '2026-04-20', '2026-10-05', '2026-11-01'],
  },
  {
    _id: 'trip_008',
    title: 'Bali Spiritual Renewal',
    location: 'Ubud & Seminyak, Bali',
    country: 'Indonesia',
    category: 'Wellness & Spiritual',
    price: 1799,
    duration: 9,
    images: ['/images/beach.jpg', '/images/suite.jpg'],
    rating: 4.8,
    reviewCount: 176,
    maxGroupSize: 8,
    description:
      'Bali\'s spiritual energy is palpable — from the incense-scented morning ceremonies at ancient temples to the rice terraces that cascade like green staircases to the valley below. This wellness retreat combines daily yoga, Ayurvedic treatments, and cultural immersion for a truly transformative journey.',
    highlights: [
      'Daily sunrise yoga in a jungle pavilion',
      'Water purification ceremony at Tirta Empul',
      'Cooking class in a family compound',
      'Rice terrace trek through Tegallalang',
      'Traditional Balinese healing session',
    ],
    itinerary: [
      { day: 1, title: 'Arrival in Ubud', description: 'Arrive, welcome ceremony, orientation, restorative yoga.' },
      { day: 2, title: 'Temple & Rice Terraces', description: 'Visit Tegallalang rice terraces, afternoon at Tirta Empul temple.' },
      { day: 3, title: 'Yoga & Healing', description: 'Sunrise yoga, traditional Balian healing session.' },
      { day: 4, title: 'Cooking & Culture', description: 'Market visit, cooking class in a Balinese family compound.' },
      { day: 5, title: 'Mount Batur Sunrise', description: 'Pre-dawn trek to Mount Batur for sunrise, hot springs.' },
      { day: 6, title: 'Seminyak Transfer', description: 'Travel to Seminyak beach, sunset at Tanah Lot temple.' },
      { day: 7, title: 'Beach & Spa', description: 'Beach day, four-hand Balinese massage, beach club sunset.' },
      { day: 8, title: 'Leisure', description: 'Free day for shopping, surfing lessons, or further relaxation.' },
      { day: 9, title: 'Departure', description: 'Final temple visit, airport transfer.' },
    ],
    inclusions: ['Boutique hotel & villa (8 nights)', 'Daily breakfast', 'Yoga sessions', 'Healing session', 'Cooking class', 'Mount Batur trek', 'All transfers'],
    exclusions: ['International flights', 'Travel insurance', 'Most lunches & dinners', 'Personal shopping'],
    pricing: [
      { type: 'Solo Traveler', price: 1799 },
      { type: 'Couple (per person)', price: 1549 },
      { type: 'Group (4+, per person)', price: 1399 },
    ],
    available: true,
    startDates: ['2026-04-10', '2026-07-01', '2026-08-15', '2026-09-05', '2026-10-20'],
  },
];

export const MOCK_BOOKINGS = [
  {
    _id: 'bk_001',
    tripId: 'trip_002',
    trip: MOCK_TRIPS[1],
    status: 'upcoming',
    travelDate: '2026-04-01',
    travelers: 2,
    totalAmount: 3300,
    paymentStatus: 'paid',
    bookingDate: '2026-01-15',
    confirmationCode: 'WA-2026-KYT-001',
  },
  {
    _id: 'bk_002',
    tripId: 'trip_001',
    trip: MOCK_TRIPS[0],
    status: 'past',
    travelDate: '2025-09-10',
    travelers: 1,
    totalAmount: 2299,
    paymentStatus: 'paid',
    bookingDate: '2025-06-20',
    confirmationCode: 'WA-2025-AMF-002',
  },
  {
    _id: 'bk_003',
    tripId: 'trip_004',
    trip: MOCK_TRIPS[3],
    status: 'upcoming',
    travelDate: '2026-11-10',
    travelers: 2,
    totalAmount: 7398,
    paymentStatus: 'paid',
    bookingDate: '2026-02-01',
    confirmationCode: 'WA-2026-MDV-003',
  },
];

export const MOCK_FAQS = [
  {
    category: 'Booking & Payment',
    questions: [
      { q: 'How do I book a trip?', a: 'Browse our destinations, select your preferred trip, choose your dates and group size, then complete the secure checkout process. You\'ll receive a confirmation email immediately.' },
      { q: 'What payment methods do you accept?', a: 'We accept all major credit/debit cards (Visa, Mastercard, Amex), PayPal, and bank transfers for bookings over $3,000.' },
      { q: 'Is my payment secure?', a: 'Absolutely. We use 256-bit SSL encryption and are PCI-DSS compliant. Your card details are never stored on our servers.' },
      { q: 'Can I pay in instalments?', a: 'Yes! For trips over $2,000, you can pay a 30% deposit to secure your booking, with the balance due 60 days before departure.' },
    ],
  },
  {
    category: 'Cancellation & Changes',
    questions: [
      { q: 'What is your cancellation policy?', a: 'Cancellations made 90+ days before departure receive a full refund. 60–89 days: 75% refund. 30–59 days: 50% refund. Under 30 days: no refund, but you can transfer to a future date.' },
      { q: 'Can I change my travel dates?', a: 'Date changes are free if made 60+ days before departure (subject to availability). Changes within 60 days incur a $150 admin fee.' },
      { q: 'What if WanderAI cancels my trip?', a: 'In the rare event we cancel, you\'ll receive a full refund plus a 20% discount on your next booking.' },
      { q: 'Is travel insurance included?', a: 'Travel insurance is not included but is strongly recommended. We partner with World Nomads and can arrange coverage at checkout.' },
    ],
  },
  {
    category: 'During Your Trip',
    questions: [
      { q: 'Who will be my guide?', a: 'All WanderAI guides are certified professionals with 5+ years of local experience, fluent in English and the local language.' },
      { q: 'What should I pack?', a: 'After booking, you\'ll receive a detailed packing list tailored to your specific trip, climate, and activities.' },
      { q: 'What happens if there\'s an emergency?', a: 'Our 24/7 emergency hotline (+1 800 987-6543) is always available. We work with local emergency services in every destination.' },
      { q: 'Are meals included?', a: 'This varies by trip. Each trip page clearly lists included meals. All dietary requirements can be accommodated with advance notice.' },
    ],
  },
  {
    category: 'About WanderAI',
    questions: [
      { q: 'How does the AI recommendation work?', a: 'Our AI analyses your travel history, preferences, budget, and travel dates to recommend the most suitable destinations and experiences uniquely for you.' },
      { q: 'Are you a licensed travel agency?', a: 'Yes. WanderAI is fully licensed and bonded, registered with IATA and ASTA, giving you complete financial protection.' },
      { q: 'Do you offer group and corporate travel?', a: 'Yes! We specialise in group travel (10+ people) and corporate retreats. Contact our dedicated team for custom quotes.' },
      { q: 'How can I become a travel partner?', a: 'We\'re always looking for exceptional local guides and hospitality partners. Email partners@wanderai.com with your proposal.' },
    ],
  },
];

export const CATEGORIES = ['All', 'Beach & Coast', 'Culture & Heritage', 'Adventure & Nature', 'Wellness & Spiritual'];

export const getTripById = (id: string) => MOCK_TRIPS.find(t => t._id === id) || null;
export const getTripsByCategory = (cat: string) =>
  cat === 'All' ? MOCK_TRIPS : MOCK_TRIPS.filter(t => t.category === cat);
export const searchTrips = (query: string) =>
  MOCK_TRIPS.filter(
    t =>
      t.title.toLowerCase().includes(query.toLowerCase()) ||
      t.location.toLowerCase().includes(query.toLowerCase()) ||
      t.country.toLowerCase().includes(query.toLowerCase()) ||
      t.category.toLowerCase().includes(query.toLowerCase())
  );
